// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert_gym_info.sql

package db

import (
	"context"
)

const insertGym = `-- name: InsertGym :exec
insert into gyms (name)
values ($1)
`

func (q *Queries) InsertGym(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertGym, name)
	return err
}
