// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert_gym_info.sql

package db

import (
	"context"
)

const insertGym = `-- name: InsertGym :exec
insert into gyms (name, auth_key)
values ($1, $2)
`

type InsertGymParams struct {
	Name    string `db:"name"`
	AuthKey string `db:"auth_key"`
}

func (q *Queries) InsertGym(ctx context.Context, arg InsertGymParams) error {
	_, err := q.db.ExecContext(ctx, insertGym, arg.Name, arg.AuthKey)
	return err
}
