// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert_session.sql

package db

import (
	"context"
)

const insertSession = `-- name: InsertSession :exec
insert into sessions (user_id, camera_id)
values ($1, $2)
`

type InsertSessionParams struct {
	UserID   int64 `db:"user_id"`
	CameraID int64 `db:"camera_id"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession, arg.UserID, arg.CameraID)
	return err
}
