// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: select_user_info.sql

package db

import (
	"context"
)

const selectUserInfo = `-- name: SelectUserInfo :one
select
  first_name,
  last_name
from users u
where id = $1
limit 1
`

type SelectUserInfoRow struct {
	FirstName string
	LastName  string
}

func (q *Queries) SelectUserInfo(ctx context.Context, id int32) (SelectUserInfoRow, error) {
	row := q.db.QueryRow(ctx, selectUserInfo, id)
	var i SelectUserInfoRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}
