// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: select_gym_info.sql

package db

import (
	"context"
)

const selectGymInfo = `-- name: SelectGymInfo :one
select
  name
from gyms u
where id = $1
limit 1
`

func (q *Queries) SelectGymInfo(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, selectGymInfo, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
