// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: select_gym_info.sql

package db

import (
	"context"
)

const selectGymIdByAuthKey = `-- name: SelectGymIdByAuthKey :one
select
  id
from gyms u
where auth_key = $1
limit 1
`

func (q *Queries) SelectGymIdByAuthKey(ctx context.Context, authKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectGymIdByAuthKey, authKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const selectGymInfo = `-- name: SelectGymInfo :one
select
  name
from gyms u
where id = $1
limit 1
`

func (q *Queries) SelectGymInfo(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, selectGymInfo, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
