services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./app.env
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./server
    container_name: server
    depends_on:
        - postgres
    restart: always
    ports:
      - "8080:8080"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
volumes:
  pgdata:
