// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// StartCameraActionParams is parameters of startCameraAction operation.
type StartCameraActionParams struct {
	CameraId ID
}

func unpackStartCameraActionParams(packed middleware.Parameters) (params StartCameraActionParams) {
	{
		key := middleware.ParameterKey{
			Name: "cameraId",
			In:   "path",
		}
		params.CameraId = packed[key].(ID)
	}
	return params
}

func decodeStartCameraActionParams(args [1]string, argsEscaped bool, r *http.Request) (params StartCameraActionParams, _ error) {
	// Decode path: cameraId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cameraId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotCameraIdVal int64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt64(val)
					if err != nil {
						return err
					}

					paramsDotCameraIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CameraId = ID(paramsDotCameraIdVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cameraId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// StopCameraActionParams is parameters of stopCameraAction operation.
type StopCameraActionParams struct {
	CameraId ID
}

func unpackStopCameraActionParams(packed middleware.Parameters) (params StopCameraActionParams) {
	{
		key := middleware.ParameterKey{
			Name: "cameraId",
			In:   "path",
		}
		params.CameraId = packed[key].(ID)
	}
	return params
}

func decodeStopCameraActionParams(args [1]string, argsEscaped bool, r *http.Request) (params StopCameraActionParams, _ error) {
	// Decode path: cameraId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cameraId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotCameraIdVal int64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt64(val)
					if err != nil {
						return err
					}

					paramsDotCameraIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CameraId = ID(paramsDotCameraIdVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cameraId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
