// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCamerasOperation        OperationName = "GetCameras"
	StartCameraActionOperation OperationName = "StartCameraAction"
	StopCameraActionOperation  OperationName = "StopCameraAction"
)
