// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCameras implements getCameras operation.
//
// GET /cameras
func (UnimplementedHandler) GetCameras(ctx context.Context) (r *CamerasList, _ error) {
	return r, ht.ErrNotImplemented
}

// StartCameraAction implements startCameraAction operation.
//
// POST /cameras/{cameraId}/ptz
func (UnimplementedHandler) StartCameraAction(ctx context.Context, req *ActionParams, params StartCameraActionParams) error {
	return ht.ErrNotImplemented
}

// StopCameraAction implements stopCameraAction operation.
//
// DELETE /cameras/{cameraId}/ptz
func (UnimplementedHandler) StopCameraAction(ctx context.Context, params StopCameraActionParams) error {
	return ht.ErrNotImplemented
}
