// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: select_opened_sessions.sql

package db

import (
	"context"
)

const selectOpenedSessions = `-- name: SelectOpenedSessions :many
select
  gym_id,
  camera_id
from sessions
where user_id = $1
`

type SelectOpenedSessionsRow struct {
	GymID    int32
	CameraID int32
}

func (q *Queries) SelectOpenedSessions(ctx context.Context, userID int32) ([]SelectOpenedSessionsRow, error) {
	rows, err := q.db.Query(ctx, selectOpenedSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectOpenedSessionsRow
	for rows.Next() {
		var i SelectOpenedSessionsRow
		if err := rows.Scan(&i.GymID, &i.CameraID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
