// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: select_gyms.sql

package db

import (
	"context"
)

const selectGyms = `-- name: SelectGyms :many
select
  id, name, created_at, updated_at
from gyms
`

func (q *Queries) SelectGyms(ctx context.Context) ([]Gym, error) {
	rows, err := q.db.Query(ctx, selectGyms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gym
	for rows.Next() {
		var i Gym
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
